# build stage
FROM cdcgov/maven:fdns as builder

COPY . /usr/src/app
RUN mvn clean package

# run stage
FROM openjdk:8-jre-alpine

ARG HL7_UTILS_PORT
ARG HL7_UTILS_FLUENTD_HOST
ARG HL7_UTILS_FLUENTD_PORT
ARG OBJECT_URL
ARG HL7_UTILS_PROXY_HOSTNAME
ARG OAUTH2_ACCESS_TOKEN_URI
ARG OAUTH2_PROTECTED_URIS
ARG OAUTH2_CLIENT_ID
ARG OAUTH2_CLIENT_SECRET
ARG SSL_VERIFYING_DISABLE

ENV HL7_UTILS_PORT ${HL7_UTILS_PORT}
ENV HL7_UTILS_FLUENTD_HOST ${HL7_UTILS_FLUENTD_HOST}
ENV HL7_UTILS_FLUENTD_PORT ${HL7_UTILS_FLUENTD_PORT}
ENV OBJECT_URL ${OBJECT_URL}
ENV HL7_UTILS_PROXY_HOSTNAME ${HL7_UTILS_PROXY_HOSTNAME}
ENV OAUTH2_ACCESS_TOKEN_URI ${OAUTH2_ACCESS_TOKEN_URI}
ENV OAUTH2_PROTECTED_URIS ${OAUTH2_PROTECTED_URIS}
ENV OAUTH2_CLIENT_ID ${OAUTH2_CLIENT_ID}
ENV OAUTH2_CLIENT_SECRET ${OAUTH2_CLIENT_SECRET}
ENV SSL_VERIFYING_DISABLE ${SSL_VERIFYING_DISABLE}

COPY --from=builder /usr/src/app/target/fdns-ms-hl7-utils-*.jar /app.jar

# pull latest
RUN apk update && apk upgrade --no-cache

# tomcat tmp
RUN chown -R 1001:0 /tmp

# don't run as root user
RUN chown 1001:0 /app.jar
RUN chmod g+rwx /app.jar
USER 1001

ENTRYPOINT java -Dserver.tomcat.protocol-header=x-forwarded-proto -Dserver.tomcat.remote-ip-header=x-forwarded-for -jar /app.jar